package com.veltravia.marketscopeai

import java.util.Locale

/**
 * Lightweight localization layer.
 *
 * The app follows the device language automatically: whatever the user's
 * phone is set to (German, Spanish, French, Portuguese, Italian, ...) the
 * UI strings covered by the dictionaries below switch to that language.
 * Anything not yet translated falls back to English, so coverage can grow
 * screen by screen without breaking anything.
 *
 * Usage in Compose: Text(t("Continue with Google"))
 * The dictionary key is always the exact English source string.
 */
object L10n {

    /** Two-letter device language, e.g. "de", lowercased; "en" when unknown. */
    val language: String = runCatching {
        Locale.getDefault().language.lowercase()
    }.getOrDefault("en")

    /** Full BCP-47 tag of the device locale, e.g. "de-DE" — sent to the backend so AI output follows the user's language. */
    val languageTag: String = runCatching {
        Locale.getDefault().toLanguageTag()
    }.getOrDefault("en")

    private val dictionaries: Map<String, Map<String, String>> = mapOf(
        "de" to de,
        "es" to es,
        "fr" to fr,
        "pt" to pt,
        "it" to it
    )

    fun t(en: String): String = dictionaries[language]?.get(en) ?: en
}

/** Shorthand used across screens. */
fun t(en: String): String = L10n.t(en)

private val de = mapOf(
    "WELCOME TO MARKETSCOPE AI" to "WILLKOMMEN BEI MARKETSCOPE AI",
    "Let's analyze your chart" to "Lass uns dein Chart analysieren",
    "Continue with Google" to "Mit Google fortfahren",
    "Google" to "Google",
    "By continuing, you agree to our " to "Mit dem Fortfahren akzeptierst du unsere ",
    "Terms of Service" to "Nutzungsbedingungen",
    "Privacy Policy" to "Datenschutzerklärung",
    "By Veltravia Technologies" to "Von Veltravia Technologies",
    "Login failed. Please try again." to "Anmeldung fehlgeschlagen. Bitte versuche es erneut.",
    "Google sign-in is temporarily unavailable. Please try again shortly." to "Die Google-Anmeldung ist vorübergehend nicht verfügbar. Bitte versuche es gleich noch einmal.",
    "Trade with data-driven confidence." to "Handle datengestützt und mit Vertrauen.",
    "News Outlook" to "Nachrichten-Ausblick",
    "Risk calculator" to "Risikorechner",
    "Community" to "Community",
    "Signals" to "Signale",
    "Saved" to "Gespeichert",
    "Share" to "Teilen",
    "Share MarketScope AI" to "MarketScope AI teilen",
    "Learning hub" to "Lernzentrum",
    "Trade Plan" to "Trade-Plan",
    "Calendar" to "Kalender",
    "Contact support" to "Support kontaktieren",
    "Notifications" to "Benachrichtigungen",
    "Show less" to "Weniger anzeigen",
    "Show more" to "Mehr anzeigen",
    "COMMUNITY" to "COMMUNITY",
    "Visit the room" to "Room ansehen",
    "Join the room today" to "Heute dem Room beitreten",
    "Loading…" to "Wird geladen…",
    "PREMIUM" to "PREMIUM",
    "FREE TRIAL" to "GRATISTEST",
    "Active" to "Aktiv",
    "Free plan" to "Kostenloser Plan",
    "Enjoy unlimited access" to "Genieße unbegrenzten Zugang",
    "View your plan in Profile" to "Deinen Plan im Profil ansehen",
    "MarketScope AI Recommended Tools" to "Empfohlene Tools von MarketScope AI",
    "Trade with real market conditions" to "Handle unter echten Marktbedingungen",
    "Our recommended broker for testing MarketScope AI's analysis." to "Unser empfohlener Broker, um die Analysen von MarketScope AI zu testen.",
    "Pull to refresh" to "Zum Aktualisieren ziehen",
    "Go further with Premium" to "Mit Premium weitergehen",
    "Included with every account" to "In jedem Konto enthalten",
    "Cancel anytime." to "Jederzeit kündbar.",
    "See what Premium unlocks" to "Sieh, was Premium freischaltet",
    "Close" to "Schließen",
    "Cancel" to "Abbrechen",
    "Could not load plans right now." to "Pläne können gerade nicht geladen werden.",
    "Subscribe with Google Play" to "Über Google Play abonnieren",
    "Subscribed" to "Abonniert",
    "Subscribing" to "Abonnement läuft",
    "Premium is now active" to "Premium ist jetzt aktiv",
    "Check subscription status" to "Abo-Status prüfen",
    "MarketScope AI is a market-research and education tool. AI analysis is for informational purposes only and is not financial advice." to "MarketScope AI ist ein Marktforschungs- und Bildungs-Tool. KI-Analysen dienen nur zur Information und stellen keine Anlageberatung dar.",
    "Please sign in to your MarketScope AI account to subscribe." to "Bitte melde dich mit deinem MarketScope AI-Konto an, um zu abonnieren.",
    "Save" to "Speichern",
    "Retry" to "Erneut versuchen",
    "Settings" to "Einstellungen",
    "Trading profile" to "Trading-Profil",
    "Saved trade plans" to "Gespeicherte Trade-Pläne",
    "Trade journal" to "Trade-Journal",
    "Screenshot guide" to "Screenshot-Anleitung",
    "Invite friends" to "Freunde einladen",
    "Help & support" to "Hilfe & Support",
    "Your Opinion" to "Deine Meinung",
    "Report a bug" to "Fehler melden",
    "Shake to report a bug" to "Schütteln, um einen Fehler zu melden",
    "Terms of service" to "Nutzungsbedingungen",
    "Privacy policy" to "Datenschutzerklärung",
    "Community guidelines" to "Community-Richtlinien",
    "Sign out" to "Abmelden",
    "Delete my account" to "Mein Konto löschen",
    "Delete Account" to "Konto löschen",
    "Log out?" to "Abmelden?",
    "You'll need to sign back in to keep using MarketScope AI." to "Du musst dich erneut anmelden, um MarketScope AI weiter zu nutzen.",
    "Log out" to "Abmelden",
    "Permanently delete account?" to "Konto dauerhaft löschen?",
    "We'll schedule your account, trade plans, and analyses for erasure in 30 days. " to "Wir planen die Löschung deines Kontos, deiner Trade-Pläne und Analysen in 30 Tagen. ",
    "I understand this action is permanent." to "Ich verstehe, dass diese Aktion dauerhaft ist.",
    "Account deletion scheduled" to "Konto-Löschung geplant",
    "Your handle" to "Dein Handle",
    "3-20 characters — lowercase letters, numbers, dots or underscores. Other traders will see it as @handle." to "3–20 Zeichen — Kleinbuchstaben, Zahlen, Punkte oder Unterstriche. Andere Trader sehen es als @Handle.",
    "e.g. euro.trader" to "z. B. euro.trader",
    "Analyses run" to "Ausgeführte Analysen",
    "Saved trades" to "Gespeicherte Trades"
)

private val es = mapOf(
    "WELCOME TO MARKETSCOPE AI" to "BIENVENIDO A MARKETSCOPE AI",
    "Let's analyze your chart" to "Analicemos tu gráfico",
    "Continue with Google" to "Continuar con Google",
    "Google" to "Google",
    "By continuing, you agree to our " to "Al continuar, aceptas nuestros ",
    "Terms of Service" to "Términos del servicio",
    "Privacy Policy" to "Política de privacidad",
    "By Veltravia Technologies" to "Por Veltravia Technologies",
    "Login failed. Please try again." to "Error al iniciar sesión. Inténtalo de nuevo.",
    "Google sign-in is temporarily unavailable. Please try again shortly." to "El inicio de sesión con Google no está disponible temporalmente. Inténtalo de nuevo en unos minutos.",
    "Trade with data-driven confidence." to "Opere con confianza basada en datos.",
    "News Outlook" to "Perspectiva de noticias",
    "Risk calculator" to "Calculadora de riesgo",
    "Community" to "Comunidad",
    "Signals" to "Señales",
    "Saved" to "Guardado",
    "Share" to "Compartir",
    "Share MarketScope AI" to "Compartir MarketScope AI",
    "Learning hub" to "Centro de aprendizaje",
    "Trade Plan" to "Plan de trading",
    "Calendar" to "Calendario",
    "Contact support" to "Contactar con soporte",
    "Notifications" to "Notificaciones",
    "Show less" to "Ver menos",
    "Show more" to "Ver más",
    "COMMUNITY" to "COMUNIDAD",
    "Visit the room" to "Visitar la sala",
    "Join the room today" to "Únete a la sala hoy",
    "Loading…" to "Cargando…",
    "PREMIUM" to "PREMIUM",
    "FREE TRIAL" to "PRUEBA GRATIS",
    "Active" to "Activo",
    "Free plan" to "Plan gratuito",
    "Enjoy unlimited access" to "Disfruta de acceso ilimitado",
    "View your plan in Profile" to "Consulta tu plan en el perfil",
    "MarketScope AI Recommended Tools" to "Herramientas recomendadas por MarketScope AI",
    "Trade with real market conditions" to "Opere con condiciones reales del mercado",
    "Our recommended broker for testing MarketScope AI's analysis." to "Nuestro bróker recomendado para probar los análisis de MarketScope AI.",
    "Pull to refresh" to "Desliza para actualizar",
    "Go further with Premium" to "Ve más allá con Premium",
    "Included with every account" to "Incluido en todas las cuentas",
    "Cancel anytime." to "Cancela cuando quieras.",
    "See what Premium unlocks" to "Descubre lo que desbloquea Premium",
    "Close" to "Cerrar",
    "Cancel" to "Cancelar",
    "Could not load plans right now." to "No se pueden cargar los planes en este momento.",
    "Subscribe with Google Play" to "Suscribirse con Google Play",
    "Subscribed" to "Suscrito",
    "Subscribing" to "Suscrito...",
    "Premium is now active" to "Premium ya está activo",
    "Check subscription status" to "Comprobar estado de la suscripción",
    "MarketScope AI is a market-research and education tool. AI analysis is for informational purposes only and is not financial advice." to "MarketScope AI es una herramienta de investigación de mercados y educación. El análisis con IA tiene fines informativos y no constituye asesoramiento financiero.",
    "Please sign in to your MarketScope AI account to subscribe." to "Inicia sesión con tu cuenta de MarketScope AI para suscribirte.",
    "Save" to "Guardar",
    "Retry" to "Reintentar",
    "Settings" to "Ajustes",
    "Trading profile" to "Perfil de trading",
    "Saved trade plans" to "Planes de trading guardados",
    "Trade journal" to "Diario de trading",
    "Screenshot guide" to "Guía de capturas",
    "Invite friends" to "Invitar amigos",
    "Help & support" to "Ayuda y soporte",
    "Your Opinion" to "Tu opinión",
    "Report a bug" to "Informar de un error",
    "Shake to report a bug" to "Agita para informar de un error",
    "Terms of service" to "Términos del servicio",
    "Privacy policy" to "Política de privacidad",
    "Community guidelines" to "Normas de la comunidad",
    "Sign out" to "Cerrar sesión",
    "Delete my account" to "Eliminar mi cuenta",
    "Delete Account" to "Eliminar cuenta",
    "Log out?" to "¿Cerrar sesión?",
    "You'll need to sign back in to keep using MarketScope AI." to "Tendrás que volver a iniciar sesión para seguir usando MarketScope AI.",
    "Log out" to "Cerrar sesión",
    "Permanently delete account?" to "¿Eliminar la cuenta permanentemente?",
    "We'll schedule your account, trade plans, and analyses for erasure in 30 days. " to "Programaremos la eliminación de tu cuenta, tus planes de trading y tus análisis en 30 días. ",
    "I understand this action is permanent." to "Entiendo que esta acción es permanente.",
    "Account deletion scheduled" to "Eliminación de cuenta programada",
    "Your handle" to "Tu usuario",
    "3-20 characters — lowercase letters, numbers, dots or underscores. Other traders will see it as @handle." to "3–20 caracteres: letras minúsculas, números, puntos o guiones bajos. Otros traders lo verán como @usuario.",
    "e.g. euro.trader" to "p. ej. euro.trader",
    "Analyses run" to "Análisis realizados",
    "Saved trades" to "Trades guardados"
)

private val fr = mapOf(
    "WELCOME TO MARKETSCOPE AI" to "BIENVENUE SUR MARKETSCOPE AI",
    "Let's analyze your chart" to "Analysons ton graphique",
    "Continue with Google" to "Continuer avec Google",
    "Google" to "Google",
    "By continuing, you agree to our " to "En continuant, tu acceptes nos ",
    "Terms of Service" to "Conditions d'utilisation",
    "Privacy Policy" to "Politique de confidentialité",
    "By Veltravia Technologies" to "Par Veltravia Technologies",
    "Login failed. Please try again." to "Échec de la connexion. Réessaie.",
    "Google sign-in is temporarily unavailable. Please try again shortly." to "La connexion Google est temporairement indisponible. Réessaie dans un instant.",
    "Trade with data-driven confidence." to "Tradez avec une confiance fondée sur les données.",
    "News Outlook" to "Perspectives d'actualités",
    "Risk calculator" to "Calculateur de risque",
    "Community" to "Communauté",
    "Signals" to "Signaux",
    "Saved" to "Enregistré",
    "Share" to "Partager",
    "Share MarketScope AI" to "Partager MarketScope AI",
    "Learning hub" to "Centre d'apprentissage",
    "Trade Plan" to "Plan de trade",
    "Calendar" to "Calendrier",
    "Contact support" to "Contacter le support",
    "Notifications" to "Notifications",
    "Show less" to "Afficher moins",
    "Show more" to "Afficher plus",
    "COMMUNITY" to "COMMUNAUTÉ",
    "Visit the room" to "Visiter le salon",
    "Join the room today" to "Rejoins le salon dès aujourd'hui",
    "Loading…" to "Chargement…",
    "PREMIUM" to "PREMIUM",
    "FREE TRIAL" to "ESSAI GRATUIT",
    "Active" to "Actif",
    "Free plan" to "Offre gratuite",
    "Enjoy unlimited access" to "Profite d'un accès illimité",
    "View your plan in Profile" to "Consulte ton offre dans le profil",
    "MarketScope AI Recommended Tools" to "Outils recommandés par MarketScope AI",
    "Trade with real market conditions" to "Trade dans de vraies conditions de marché",
    "Our recommended broker for testing MarketScope AI's analysis." to "Notre courtier recommandé pour tester les analyses de MarketScope AI.",
    "Pull to refresh" to "Tirer pour actualiser",
    "Go further with Premium" to "Va plus loin avec Premium",
    "Included with every account" to "Inclus dans chaque compte",
    "Cancel anytime." to "Résiliable à tout moment.",
    "See what Premium unlocks" to "Découvre ce que Premium débloque",
    "Close" to "Fermer",
    "Cancel" to "Annuler",
    "Could not load plans right now." to "Impossible de charger les offres pour le moment.",
    "Subscribe with Google Play" to "S'abonner via Google Play",
    "Subscribed" to "Abonné",
    "Subscribing" to "Abonnement...",
    "Premium is now active" to "Premium est maintenant actif",
    "Check subscription status" to "Vérifier l'état de l'abonnement",
    "MarketScope AI is a market-research and education tool. AI analysis is for informational purposes only and is not financial advice." to "MarketScope AI est un outil de recherche de marché et d'éducation. L'analyse par IA est fournie à titre informatif et ne constitue pas un conseil financier.",
    "Please sign in to your MarketScope AI account to subscribe." to "Connecte-toi à ton compte MarketScope AI pour t'abonner.",
    "Save" to "Enregistrer",
    "Retry" to "Réessayer",
    "Settings" to "Réglages",
    "Trading profile" to "Profil de trading",
    "Saved trade plans" to "Plans de trade enregistrés",
    "Trade journal" to "Journal de trading",
    "Screenshot guide" to "Guide des captures",
    "Invite friends" to "Inviter des amis",
    "Help & support" to "Aide et support",
    "Your Opinion" to "Ton avis",
    "Report a bug" to "Signaler un bug",
    "Shake to report a bug" to "Secouer pour signaler un bug",
    "Terms of service" to "Conditions d'utilisation",
    "Privacy policy" to "Politique de confidentialité",
    "Community guidelines" to "Règles de la communauté",
    "Sign out" to "Se déconnecter",
    "Delete my account" to "Supprimer mon compte",
    "Delete Account" to "Supprimer le compte",
    "Log out?" to "Se déconnecter ?",
    "You'll need to sign back in to keep using MarketScope AI." to "Tu devras te reconnecter pour continuer à utiliser MarketScope AI.",
    "Log out" to "Se déconnecter",
    "Permanently delete account?" to "Supprimer définitivement le compte ?",
    "We'll schedule your account, trade plans, and analyses for erasure in 30 days. " to "Nous programmerons l'effacement de ton compte, de tes plans de trade et de tes analyses dans 30 jours. ",
    "I understand this action is permanent." to "Je comprends que cette action est définitive.",
    "Account deletion scheduled" to "Suppression du compte programmée",
    "Your handle" to "Ton identifiant",
    "3-20 characters — lowercase letters, numbers, dots or underscores. Other traders will see it as @handle." to "3–20 caractères : lettres minuscules, chiffres, points ou tirets bas. Les autres traders le verront sous la forme @identifiant.",
    "e.g. euro.trader" to "ex. euro.trader",
    "Analyses run" to "Analyses effectuées",
    "Saved trades" to "Trades enregistrés"
)

private val pt = mapOf(
    "WELCOME TO MARKETSCOPE AI" to "BEM-VINDO AO MARKETSCOPE AI",
    "Let's analyze your chart" to "Vamos analisar o seu gráfico",
    "Continue with Google" to "Continuar com Google",
    "Google" to "Google",
    "By continuing, you agree to our " to "Ao continuar, você aceita nossos ",
    "Terms of Service" to "Termos do serviço",
    "Privacy Policy" to "Política de privacidade",
    "By Veltravia Technologies" to "Por Veltravia Technologies",
    "Login failed. Please try again." to "Falha no login. Tente novamente.",
    "Google sign-in is temporarily unavailable. Please try again shortly." to "O login com Google está temporariamente indisponível. Tente novamente em instantes.",
    "Trade with data-driven confidence." to "Opere com confiança baseada em dados.",
    "News Outlook" to "Panorama de notícias",
    "Risk calculator" to "Calculadora de risco",
    "Community" to "Comunidade",
    "Signals" to "Sinais",
    "Saved" to "Salvo",
    "Share" to "Compartilhar",
    "Share MarketScope AI" to "Compartilhar o MarketScope AI",
    "Learning hub" to "Central de aprendizado",
    "Trade Plan" to "Plano de trade",
    "Calendar" to "Calendário",
    "Contact support" to "Contatar o suporte",
    "Notifications" to "Notificações",
    "Show less" to "Mostrar menos",
    "Show more" to "Mostrar mais",
    "COMMUNITY" to "COMUNIDADE",
    "Visit the room" to "Visitar a sala",
    "Join the room today" to "Entre na sala hoje",
    "Loading…" to "Carregando…",
    "PREMIUM" to "PREMIUM",
    "FREE TRIAL" to "TESTE GRÁTIS",
    "Active" to "Ativo",
    "Free plan" to "Plano gratuito",
    "Enjoy unlimited access" to "Desfrute de acesso ilimitado",
    "View your plan in Profile" to "Veja seu plano no perfil",
    "MarketScope AI Recommended Tools" to "Ferramentas recomendadas pelo MarketScope AI",
    "Trade with real market conditions" to "Opere em condições reais de mercado",
    "Our recommended broker for testing MarketScope AI's analysis." to "Nosso corretor recomendado para testar as análises do MarketScope AI.",
    "Pull to refresh" to "Puxe para atualizar",
    "Go further with Premium" to "Vá além com o Premium",
    "Included with every account" to "Incluído em todas as contas",
    "Cancel anytime." to "Cancele quando quiser.",
    "See what Premium unlocks" to "Veja o que o Premium desbloqueia",
    "Close" to "Fechar",
    "Cancel" to "Cancelar",
    "Could not load plans right now." to "Não foi possível carregar os planos agora.",
    "Subscribe with Google Play" to "Assinar pelo Google Play",
    "Subscribed" to "Assinado",
    "Subscribing" to "Assinando...",
    "Premium is now active" to "O Premium já está ativo",
    "Check subscription status" to "Verificar status da assinatura",
    "MarketScope AI is a market-research and education tool. AI analysis is for informational purposes only and is not financial advice." to "O MarketScope AI é uma ferramenta de pesquisa de mercado e educação. A análise por IA tem caráter informativo e não constitui orientação financeira.",
    "Please sign in to your MarketScope AI account to subscribe." to "Entre na sua conta do MarketScope AI para assinar.",
    "Save" to "Salvar",
    "Retry" to "Tentar novamente",
    "Settings" to "Configurações",
    "Trading profile" to "Perfil de trading",
    "Saved trade plans" to "Planos de trade salvos",
    "Trade journal" to "Diário de trading",
    "Screenshot guide" to "Guia de capturas",
    "Invite friends" to "Convidar amigos",
    "Help & support" to "Ajuda e suporte",
    "Your Opinion" to "Sua opinião",
    "Report a bug" to "Reportar um bug",
    "Shake to report a bug" to "Agite para reportar um bug",
    "Terms of service" to "Termos do serviço",
    "Privacy policy" to "Política de privacidade",
    "Community guidelines" to "Diretrizes da comunidade",
    "Sign out" to "Sair",
    "Delete my account" to "Excluir minha conta",
    "Delete Account" to "Excluir conta",
    "Log out?" to "Sair?",
    "You'll need to sign back in to keep using MarketScope AI." to "Será necessário entrar novamente para continuar usando o MarketScope AI.",
    "Log out" to "Sair",
    "Permanently delete account?" to "Excluir a conta permanentemente?",
    "We'll schedule your account, trade plans, and analyses for erasure in 30 days. " to "Agendaremos a exclusão da sua conta, planos de trade e análises em 30 dias. ",
    "I understand this action is permanent." to "Entendo que esta ação é permanente.",
    "Account deletion scheduled" to "Exclusão de conta agendada",
    "Your handle" to "Seu @",
    "3-20 characters — lowercase letters, numbers, dots or underscores. Other traders will see it as @handle." to "3–20 caracteres: letras minúsculas, números, pontos ou underlines. Outros traders verão como @identificador.",
    "e.g. euro.trader" to "ex.: euro.trader",
    "Analyses run" to "Análises realizadas",
    "Saved trades" to "Trades salvos"
)

private val it = mapOf(
    "WELCOME TO MARKETSCOPE AI" to "BENVENUTO SU MARKETSCOPE AI",
    "Let's analyze your chart" to "Analizziamo il tuo grafico",
    "Continue with Google" to "Continua con Google",
    "Google" to "Google",
    "By continuing, you agree to our " to "Continuando accetti i nostri ",
    "Terms of Service" to "Termini di servizio",
    "Privacy Policy" to "Informativa sulla privacy",
    "By Veltravia Technologies" to "Di Veltravia Technologies",
    "Login failed. Please try again." to "Accesso non riuscito. Riprova.",
    "Google sign-in is temporarily unavailable. Please try again shortly." to "L'accesso con Google è temporaneamente non disponibile. Riprova tra poco.",
    "Trade with data-driven confidence." to "Fai trading con sicurezza basata sui dati.",
    "News Outlook" to "Panoramica delle notizie",
    "Risk calculator" to "Calcolatore del rischio",
    "Community" to "Community",
    "Signals" to "Segnali",
    "Saved" to "Salvati",
    "Share" to "Condividi",
    "Share MarketScope AI" to "Condividi MarketScope AI",
    "Learning hub" to "Centro di apprendimento",
    "Trade Plan" to "Piano di trading",
    "Calendar" to "Calendario",
    "Contact support" to "Contatta il supporto",
    "Notifications" to "Notifiche",
    "Show less" to "Mostra meno",
    "Show more" to "Mostra altro",
    "COMMUNITY" to "COMMUNITY",
    "Visit the room" to "Visita la stanza",
    "Join the room today" to "Entra nella stanza oggi",
    "Loading…" to "Caricamento…",
    "PREMIUM" to "PREMIUM",
    "FREE TRIAL" to "PROVA GRATUITA",
    "Active" to "Attivo",
    "Free plan" to "Piano gratuito",
    "Enjoy unlimited access" to "Goditi accesso illimitato",
    "View your plan in Profile" to "Vedi il tuo piano nel profilo",
    "MarketScope AI Recommended Tools" to "Strumenti consigliati da MarketScope AI",
    "Trade with real market conditions" to "Fai trading in condizioni di mercato reali",
    "Our recommended broker for testing MarketScope AI's analysis." to "Il nostro broker consigliato per testare le analisi di MarketScope AI.",
    "Pull to refresh" to "Trascina per aggiornare",
    "Go further with Premium" to "Vai oltre con Premium",
    "Included with every account" to "Incluso in ogni account",
    "Cancel anytime." to "Disdici quando vuoi.",
    "See what Premium unlocks" to "Scopri cosa sblocca Premium",
    "Close" to "Chiudi",
    "Cancel" to "Annulla",
    "Could not load plans right now." to "Impossibile caricare i piani in questo momento.",
    "Subscribe with Google Play" to "Abbonati con Google Play",
    "Subscribed" to "Abbonato",
    "Subscribing" to "Abbonamento...",
    "Premium is now active" to "Premium ora è attivo",
    "Check subscription status" to "Verifica stato abbonamento",
    "MarketScope AI is a market-research and education tool. AI analysis is for informational purposes only and is not financial advice." to "MarketScope AI è uno strumento di ricerca di mercato ed educazione. L'analisi con IA ha scopo informativo e non costituisce consulenza finanziaria.",
    "Please sign in to your MarketScope AI account to subscribe." to "Accedi al tuo account MarketScope AI per abbonarti.",
    "Save" to "Salva",
    "Retry" to "Riprova",
    "Settings" to "Impostazioni",
    "Trading profile" to "Profilo di trading",
    "Saved trade plans" to "Piani di trading salvati",
    "Trade journal" to "Diario di trading",
    "Screenshot guide" to "Guida agli screenshot",
    "Invite friends" to "Invita amici",
    "Help & support" to "Aiuto e supporto",
    "Your Opinion" to "La tua opinione",
    "Report a bug" to "Segnala un bug",
    "Shake to report a bug" to "Scuoti per segnalare un bug",
    "Terms of service" to "Termini di servizio",
    "Privacy policy" to "Informativa sulla privacy",
    "Community guidelines" to "Linee guida della community",
    "Sign out" to "Esci",
    "Delete my account" to "Elimina il mio account",
    "Delete Account" to "Elimina account",
    "Log out?" to "Vuoi uscire?",
    "You'll need to sign back in to keep using MarketScope AI." to "Dovrai accedere di nuovo per continuare a usare MarketScope AI.",
    "Log out" to "Esci",
    "Permanently delete account?" to "Eliminare definitivamente l'account?",
    "We'll schedule your account, trade plans, and analyses for erasure in 30 days. " to "Programmeremo la cancellazione del tuo account, dei piani di trading e delle analisi entro 30 giorni. ",
    "I understand this action is permanent." to "Capisco che questa azione è permanente.",
    "Account deletion scheduled" to "Eliminazione dell'account programmata",
    "Your handle" to "Il tuo handle",
    "3-20 characters — lowercase letters, numbers, dots or underscores. Other traders will see it as @handle." to "3–20 caratteri: lettere minuscole, numeri, punti o trattini bassi. Gli altri trader lo vedranno come @handle.",
    "e.g. euro.trader" to "es. euro.trader",
    "Analyses run" to "Analisi effettuate",
    "Saved trades" to "Trade salvati"
)
